disabled_rules: # 실행에서 제외할 룰 식별자
    - line_length
    - multiple_closures_with_trailing_closure
    - leading_whitespace
    - trailing_whitespace
    - vertical_whitespace
    - function_body_length
    - cyclomatic_complexity
    - no_space_in_method_call
    - type_body_length
    
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨

excluded: # 린트 과정에서 무시할 파일. included 보다 우선순위
- Pods
