# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'RollingPaper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RollingPaper
  pod 'SnapKit'
  pod 'CombineCocoa'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'
  pod 'SwiftLint', '0.39.1'
end
