name: CI on dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: CocoaPod Install
      run: |
        cd ./RollingPaper
        pod install
    - name: Select Xcode Verson
      run: |
        sudo xcode-select --switch '/Applications/Xcode_13.3.1.app//Contents/Developer'
    - name: Build & Test (xcodeproj)
      run: |
        xcodebuild build \
        -workspace RollingPaper/RollingPaper.xcworkspace \
        -scheme RollingPaper -destination 'platform=iOS Simulator,name=iPad mini (6th generation),OS=15.4'
